name: misspell

on: [push, pull_request]

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:

      - name: check out code
        uses: actions/checkout@v2

      - name: check error
        uses: sobolevn/misspell-fixer-action@master

      - name: create PR
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}