name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: replacer
            asset_name: replacer-linux-amd64
          - os: windows-latest
            artifact_name: replacer.exe
            asset_name: replacer-windows-amd64
          - os: macos-latest
            artifact_name: replacer
            asset_name: replacer-macos-amd64

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: "1.17"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: |
        echo ${{ github.ref }} | cut -d / -f 3 >> tag
        go build -ldflags="-X 'main.version=$(cat tag)'" -o ${{ matrix.artifact_name }}

    - name: Upload binaries 
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
